/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 16 16:32:48 GMT 2020
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IfEquality_ESTest extends IfEquality_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IfEquality<Object> ifEquality0 = new IfEquality<Object>();
      boolean boolean0 = ifEquality0.ifEquality(5);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IfEquality<String> ifEquality0 = new IfEquality<String>();
      boolean boolean0 = ifEquality0.ifEquality(6598);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IfEquality<Object> ifEquality0 = new IfEquality<Object>();
      boolean boolean0 = ifEquality0.ifEquality((-1194));
      assertTrue(boolean0);
  }
}
