/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 18 16:08:27 GMT 2020
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParameterMutatorInEachBranch_ESTest extends ParameterMutatorInEachBranch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParameterMutatorInEachBranch parameterMutatorInEachBranch0 = new ParameterMutatorInEachBranch();
      Person person0 = new Person("", "");
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
      person0.cats.addAll(1, (Collection<? extends Cat>) person0.cats);
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParameterMutatorInEachBranch parameterMutatorInEachBranch0 = new ParameterMutatorInEachBranch();
      // Undeclared exception!
      try { 
        parameterMutatorInEachBranch0.parameterMutatorInEachBranch((Person) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ParameterMutatorInEachBranch", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParameterMutatorInEachBranch parameterMutatorInEachBranch0 = new ParameterMutatorInEachBranch();
      Person person0 = new Person("", "");
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
      parameterMutatorInEachBranch0.parameterMutatorInEachBranch(person0);
  }
}
