/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 18 16:10:01 GMT 2020
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Person_ESTest extends Person_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Person person0 = new Person("", "");
      person0.cats = null;
      ArrayList<Cat> arrayList0 = person0.getCats();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Person person0 = new Person("", "");
      Cat cat0 = new Cat();
      person0.cats.add(cat0);
      ArrayList<Cat> arrayList0 = person0.getCats();
      assertEquals(1, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Person person0 = new Person("", "");
      ArrayList<Cat> arrayList0 = person0.getCats();
      assertEquals(0, arrayList0.size());
  }
}
