/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 17 09:17:27 GMT 2020
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrivateMethodCalled_ESTest extends PrivateMethodCalled_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrivateMethodCalled privateMethodCalled0 = new PrivateMethodCalled();
      int int0 = privateMethodCalled0.publicMethod(5);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PrivateMethodCalled privateMethodCalled0 = new PrivateMethodCalled();
      int int0 = privateMethodCalled0.publicMethod(2);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PrivateMethodCalled privateMethodCalled0 = new PrivateMethodCalled();
      int int0 = privateMethodCalled0.publicMethod(477);
      assertEquals(2, int0);
  }
}
