/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 22 09:57:37 GMT 2020
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.IfNumberInequality;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IfNumberInequality_ESTest extends IfNumberInequality_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IfNumberInequality ifNumberInequality0 = new IfNumberInequality();
      double double0 = ifNumberInequality0.ifNumberInequality(5.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IfNumberInequality ifNumberInequality0 = new IfNumberInequality();
      double double0 = ifNumberInequality0.ifNumberInequality(3454.369926147595);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IfNumberInequality ifNumberInequality0 = new IfNumberInequality();
      double double0 = ifNumberInequality0.ifNumberInequality(0.0);
      assertEquals(1.0, double0, 0.01);
  }
}
